name: Publish to NPM and GitHub Package Registry

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # No cache since individual packages don't have lock files
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build
      
      - name: Test
        run: npm test
        continue-on-error: true

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js for NPM
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          # No cache since individual packages don't have lock files
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build
      
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-github:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js for GitHub Package Registry
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          # No cache since individual packages don't have lock files
      
      - name: Install dependencies
        run: npm install
      
      - name: Build  
        run: npm run build
      
      - name: Configure package.json for GitHub Package Registry
        run: |
          # Backup original package.json
          cp package.json package.json.backup
          # Add publishConfig for GitHub Package Registry
          node -e "
            const fs = require('fs');
            const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
            pkg.publishConfig = {
              '@gaddario98:registry': 'https://npm.pkg.github.com',
              'access': 'public'
            };
            pkg.repository = pkg.repository || 'https://github.com/gaddario98/' + pkg.name.replace('@gaddario98/', '');
            fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "
      
      - name: Publish to GitHub Package Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Restore original package.json
        run: mv package.json.backup package.json
        if: always()